python -u main.py --type_GCN 'structured' --dataset 'actor' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_act.txt
python -u main.py --type_GCN 'structured' --dataset 'chameleon' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_cham.txt
python -u main.py --type_GCN 'structured' --dataset 'squirrel' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_sqr.txt
python -u main.py --type_GCN 'structured' --dataset 'texas' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_tex.txt
python -u main.py --type_GCN 'structured' --dataset 'wisconsin' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_wis.txt
python -u main.py --type_GCN 'structured' --dataset 'cornell' --activation 'relu' --splits 10 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.2 --dropout 0.4 --w_decay 0.001 --device 'cuda:0' | tee test_cor.txt


python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'arxiv' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_arxiv.txt
python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'penn94' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_penn94.txt
python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'genius' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_genius.txt
python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'twitch' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_twitch.txt
python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'pokec' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_pokec.txt
python -u Large_Scale/main_large.py --type_GCN 'structured' --dataset 'snap' --loader_params 100 --activation 'relu' --splits 5 --lr 0.01 --seed 0 --hidden_layers 64 --hidden_dim 256 --train_iter 200 --test_iter 10 --use_saved_model False --alpha 0.5 --theta 2 --dropout 0.6 --w_decay 0.0005 --device 'cuda:0' | tee test_snap.txt



